In [4]:
import pandas as pd

In [6]:
dataset = pd.read_csv('/Users/adminuser/Documents/mir4data/mir4_data/processed/final_dataset.csv')

## First glance at data

In [8]:
dataset.head()

                 name     class  level   power  price        date
0  E20022LadyJ250250h    taoist    135  315764   3050  2025-06-02
1             tt12472  sorcerer    152  369027   2800  2025-06-02
2          Para1b1nh4   warrior     75  106982    280  2025-06-02
3         pinguinha88  sorcerer    154  414522   7645  2025-06-02
4       Kengassa24417  arbalist    148  368492   2025  2025-06-02

In [10]:
dataset.shape[0]

4151

In [12]:
dataset.columns

Index(['name', 'class', 'level', 'power', 'price', 'date'], dtype='object')

In [14]:
dataset.dtypes

name     object
class    object
level     int64
power     int64
price     int64
date     object
dtype: object

In [16]:
dataset.value_counts(subset="class")

class
arbalist     1374
taoist        994
sorcerer      575
warrior       533
lancer        412
darkist       218
lionheart      45
Name: count, dtype: int64

In [18]:
dataset["power"].min()

np.int64(100009)

In [20]:
dataset["power"].max()

np.int64(788671)

In [22]:
dataset["power"].mean()

np.float64(284641.20428812335)

In [38]:
dataset[["name", "class", "power"]].sort_values(by=["power"], ascending=False).head(3)

             name     class   power
2235      wqsmmkk   warrior  788671
2153  DCdionzinho  arbalist  748901
4041    DCbabytwo  sorcerer  746740